version: "3.8"
services:
  php:
    build:
      context: "./config/php-apache/"
      dockerfile: Dockerfile
    restart: always
    volumes:
    - "./public:/var/www/html"
    ports:
    - "3000:80"
    links:
      - "mysql"
  mysql:
    image: mysql:5.7
    command: "--default-authentication-plugin=mysql_native_password"
    restart: always
    volumes:
      - "./config/mysql:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=prt_db
      - MSQL_USER=dungbk
      - MYSQL_PASSWORD=123456
    ports:
    - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
      - PMA_PORT=3306
    links:
      - mysql
    restart: always
    ports:
    - "4040:80"
    volumes:
    - "./config/phpmyadmin/sessions:/sessions"
